name = "IMO2025"
version = "0.1.0"
defaultTargets = ["IMO2025P3", "IMO2025P4", "IMO2025P5", "IMO2025P6"]

[leanOptions]
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0-rc2"

[[lean_lib]]
name = "IMO2025P3"

[[lean_lib]]
name = "IMO2025P4"

[[lean_lib]]
name = "IMO2025P5"

[[lean_lib]]
name = "IMO2025P6"
